services:
  hyrance-backend:
    container_name: backend
    image: hyrance-backend
    build: ./backend  
    ports:
      - "3000:3000"  
    volumes:
      - ./backend:/express-docker
    networks:
      - neto       
    depends_on:
      - hyrance-mongo 

  hyrance-mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #   MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}   
    # command: mongod --auth --bind_ip_all 
    command: mongod  
    volumes:
      - mongo-data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - neto  

  hyrance-frontend:
    container_name: frontend
    build:   
      context: ./frontend  
    ports:
      - "8080:80" 
    depends_on:
      - hyrance-mongo  
      - hyrance-backend             

volumes:
  mongo-data:

networks:
  neto:
    driver: bridge




   